"""CriticSkillBank: persistent store for self-critic distilled optimal chains."""
from __future__ import annotations

import os
from typing import Optional

from ..shared.storage import JSONSkillStore


class CriticSkillBank:
    """Stores counterfactual optimal chains generated by self-critic distillation.

    Each record captures:
    - The original (successful but possibly suboptimal) tool chain
    - The LLM-suggested optimal chain with fewer/better steps
    - A natural-language critique explaining the improvement
    - task_type for filtered retrieval
    """

    def __init__(self, store_dir: str):
        os.makedirs(store_dir, exist_ok=True)
        self._store = JSONSkillStore(os.path.join(store_dir, "critic_skills.json"))

    def add(
        self,
        task_type: str,
        original_chain: list[str],
        optimal_chain: list[str],
        critique: str,
        redundant_steps: list[str],
        source_tasks: Optional[list[str]] = None,
    ) -> Optional[str]:
        """Save a critic skill; return skill_id or None if duplicate content."""
        content = (
            f"Task type: {task_type}\n"
            f"Original chain: {' → '.join(original_chain)}\n"
            f"Optimized chain: {' → '.join(optimal_chain)}\n"
            f"Critique: {critique}\n"
            f"Redundant steps: {', '.join(redundant_steps) or 'none'}"
        )
        return self._store.save_if_unique({
            "content": content,
            "task_type": task_type,
            "original_chain": original_chain,
            "optimal_chain": optimal_chain,
            "redundant_steps": redundant_steps,
            "tags": optimal_chain[:3] + [task_type],
            "source_tasks": source_tasks or [],
        })

    def load_all(self) -> list[dict]:
        return self._store.load_all()

    def count(self) -> int:
        return self._store.count()

    def clear(self) -> None:
        self._store.clear()
