"""Temporary Chinese tool descriptions for frontend testing.

This module is intentionally isolated so the testing-only Chinese text can be
removed before the tools-only PR is submitted.
"""

from __future__ import annotations


CHINESE_TOOL_DESCRIPTIONS: dict[str, str] = {
    "disaster_response.accessibility_map": "根据道路通行栅格和兴趣点位置生成到最近兴趣点的可达性时间图。",
    "disaster_response.building_damage_stats": "结合变化检测栅格和建筑物轮廓 GeoJSON 统计建筑受损情况。",
    "disaster_response.calc_flow_direction": "根据 DEM 高程栅格计算 D8 水流方向图。",
    "disaster_response.calc_slope": "根据 DEM 高程栅格计算地形坡度，可输出角度或百分比。",
    "disaster_response.fire_spread_forecast": "基于植被覆盖、起火点和风场参数模拟野火扩散范围。",
    "disaster_response.flood_route_astar": "计算考虑洪水掩膜惩罚的 A* 救援路线。",
    "disaster_response.population_exposure": "叠加灾害风险栅格和人口栅格，估算暴露人口空间分布。",
    "disaster_response.zonal_stats": "对栅格数据按 GeoJSON 面区域计算均值、总和、最大值等统计量。",
    "drone_video.extract_frames": "从无人机视频中按时间范围和帧率抽取图片帧。",
    "drone_video.parse_telemetry": "解析 DJI CSV、GPX 或 MAVLink JSON 飞行轨迹数据。",
    "drone_video.pixel_to_gps": "根据像素位置、无人机位置、高度和相机视场估算地面 GPS 坐标。",
    "earth_sci.calculate_ati": "根据昼夜温度和反照率计算表观热惯量。",
    "earth_sci.calculate_lst_mc": "使用多通道热红外亮温计算地表温度。",
    "earth_sci.calculate_lst_sc": "使用单通道亮温、红光和近红外数据计算地表温度。",
    "earth_sci.calculate_modis_day_night": "结合 MODIS 昼夜亮温和发射率计算地表温度。",
    "earth_sci.calculate_pwv": "利用 MODIS 多个波段估算可降水量。",
    "earth_sci.calculate_sea_ice": "根据微波亮温估算海冰密集度。",
    "earth_sci.calculate_split_window": "使用分裂窗算法计算地表温度或水汽参数。",
    "earth_sci.calculate_tes": "使用温度发射率分离方法估算地表温度。",
    "earth_sci.calculate_ttm": "使用温度时间模型处理热红外波段并输出结果栅格。",
    "earth_sci.calculate_turbidity": "根据红光波段估算水体浊度。",
    "earth_sci.microwave_ddm": "使用双差分微波方法计算土壤水分等地表参数。",
    "earth_sci.microwave_dpdm": "使用双极化差分微波方法反演地表参数。",
    "earth_sci.microwave_multi_freq": "组合多个频率的微波亮温进行多频差分分析。",
    "earth_sci.microwave_prm": "使用极化比微波方法反演地表参数。",
    "earth_sci.stats_lst_ndvi": "按 NDVI 区间统计地表温度特征。",
    "geo_perception.add_text": "在图片上绘制文字标注并输出标注后的图片。",
    "geo_perception.bbox_area": "计算一个或多个边界框的面积。",
    "geo_perception.bbox_expand": "按半径或比例扩展边界框范围。",
    "geo_perception.bbox_to_centroid": "将边界框转换为中心点坐标。",
    "geo_perception.centroid_distance_extremes": "计算中心点之间的距离极值。",
    "geo_perception.change_os_detect": "使用 ChangeOS 模型检测前后时相遥感影像变化。",
    "geo_perception.draw_bboxes": "在图片上绘制目标检测边界框并输出图片。",
    "geo_perception.instructsam": "用 InstructSAM 根据文本提示进行目标计数或分割。",
    "geo_perception.mscn_classify": "使用 MSCN 模型进行遥感场景分类。",
    "geo_perception.ocr_extract": "从图片中提取文字内容。",
    "geo_perception.remoteclip_analysis": "使用 RemoteCLIP 计算图片与文本查询的匹配结果。",
    "geo_perception.remotesam": "使用 RemoteSAM 执行遥感图像目标分割等任务。",
    "geo_perception.sam2_segment": "使用 SAM2 对输入图像进行分割。",
    "geo_perception.sm3det_detect": "使用 SM3Det 进行多类别遥感目标检测。",
    "geo_perception.strip_rcnn_detect": "使用 Strip R-CNN 检测条带状或旋转目标。",
    "geo_perception.vlm_analyze": "使用视觉语言模型分析一张或多张图像。",
    "geo_raster.apply_cloud_mask": "根据 QA 或 SCL 栅格对地表反射率栅格进行云掩膜处理。",
    "geo_raster.calc_snow_loss_stats": "统计二值雪损或损失图中的像元数量和比例。",
    "geo_raster.calculate_evi": "根据近红外、红光和蓝光波段计算增强植被指数 EVI。",
    "geo_raster.calculate_frp": "根据 FRP 栅格阈值生成火点或火辐射功率掩膜。",
    "geo_raster.calculate_fvc": "根据 NDVI 或红光近红外波段计算植被覆盖度 FVC。",
    "geo_raster.calculate_index": "根据两个波段计算通用光谱指数，如 NDVI 类指数。",
    "geo_raster.calculate_wri": "根据绿光、红光、近红外和短波红外计算水体相关指数 WRI。",
    "geo_raster.compute_tvdi": "根据 NDVI 和地表温度计算温度植被干旱指数 TVDI。",
    "geo_raster.count_above_threshold": "统计栅格中超过指定阈值的像元数量。",
    "geo_raster.count_fire_pixels": "统计一张或多张火点栅格中的火像元数量。",
    "geo_raster.count_skeleton_contours": "对二值图像骨架或轮廓数量进行统计。",
    "geo_raster.create_fire_increase_map": "比较灾前和灾后火点掩膜，生成新增火区栅格。",
    "geo_raster.get_percentile_value": "计算栅格有效像元的指定百分位数。",
    "geo_raster.get_raster_info": "读取栅格的尺寸、范围、坐标系、分辨率等元信息。",
    "geo_raster.hotspot_percentage": "计算超过阈值的热点像元比例。",
    "geo_raster.identify_fire_prone_areas": "根据火点时间序列识别高火险区域。",
    "geo_raster.raster_average": "对多张同尺寸栅格计算逐像元平均值。",
    "geo_raster.raster_diff": "计算两张同尺寸栅格的逐像元差值。",
    "geo_raster.raster_stats": "统计栅格的最小值、最大值、均值等基础指标。",
    "geo_raster.threshold_segmentation": "根据阈值将连续栅格分割为二值掩膜。",
    "geo_statistics.batch_raster_stats": "批量计算多张栅格的基础统计量。",
    "geo_statistics.calc_cv": "计算栅格有效像元的变异系数。",
    "geo_statistics.calc_kurtosis": "计算栅格有效像元的峰度。",
    "geo_statistics.calc_percentile": "计算栅格有效像元的指定百分位数。",
    "geo_statistics.calc_skewness": "计算栅格有效像元的偏度。",
    "geo_statistics.celsius_to_kelvin": "将摄氏度转换为开尔文温度。",
    "geo_statistics.count_images_exceeding": "统计多张栅格中超过阈值比例条件的影像数量。",
    "geo_statistics.count_pixels_condition": "统计满足数值范围条件的像元数量。",
    "geo_statistics.intersection_percentage": "计算两张阈值掩膜的交集比例。",
    "geo_statistics.kelvin_to_celsius": "将开尔文温度转换为摄氏度。",
    "geo_statistics.mean_of_means": "计算多张栅格均值的平均值。",
    "geo_statistics.multi_band_threshold": "对多波段阈值条件进行组合统计分析。",
    "geo_statistics.percentage_change": "计算两个数值之间的百分比变化。",
    "geo_statistics.scalar_arithmetic": "对两个标量执行加减乘除等算术运算。",
    "geo_statistics.threshold_ratio": "计算栅格中超过阈值的像元比例。",
    "geoanalysis.analyze_hotspot_direction": "分析二值热点图中热点的空间方向趋势。",
    "geoanalysis.autocorrelation_function": "计算时间序列的自相关函数。",
    "geoanalysis.coefficient_of_variation": "计算输入数值序列的变异系数。",
    "geoanalysis.compute_linear_trend": "对时间序列拟合线性趋势并返回斜率等指标。",
    "geoanalysis.count_spikes": "统计时间序列中的异常尖峰数量。",
    "geoanalysis.detect_change_points": "检测时间序列中的突变点。",
    "geoanalysis.detect_seasonality_acf": "基于自相关函数判断时间序列季节性。",
    "geoanalysis.getis_ord_gi_star": "计算 Getis-Ord Gi* 热点统计并输出热点栅格。",
    "geoanalysis.kurtosis": "计算输入数值序列的峰度。",
    "geoanalysis.mann_kendall_test": "执行 Mann-Kendall 趋势显著性检验。",
    "geoanalysis.percentage_change": "计算新旧数值之间的百分比变化。",
    "geoanalysis.sens_slope": "使用 Sen 斜率估计时间序列趋势强度。",
    "geoanalysis.skewness": "计算输入数值序列的偏度。",
    "geoanalysis.stl_decompose": "对时间序列进行 STL 趋势、季节和残差分解。",
    "osm_gis.add_pois_layer": "根据 OSM 标签查询兴趣点并写入 GeoPackage 图层。",
    "osm_gis.compute_route_dist": "基于道路网络计算 GeoPackage 中源点到目标点的路网距离。",
    "osm_gis.get_area_boundary": "从地名或边界框获取区域边界并保存为 GeoPackage。",
    "osm_gis.get_bbox_from_raster": "从 GeoTIFF 栅格读取空间边界框。",
    "raster_viewer.inspect_geotiff": "查看 GeoTIFF 或 TIFF 文件的尺寸、坐标范围、波段统计、有效像元、空值和直方图。",
}


def append_chinese_description(slug: str, description: str) -> str:
    """Append a temporary Chinese description to selected new tools."""
    chinese = CHINESE_TOOL_DESCRIPTIONS.get(slug)
    if not chinese or "中文：" in description:
        return description
    return f"{description}\n\n中文：{chinese}"
