"""CausalEvoPromptInjector: augments system prompt with CTFM-derived causal plan.

Ablation modes (controlled by use_ablation):
  None           — Full CausalEvo: CTFM + CCA + causal graph synthesis
  "no_cca"       — Ablation A: CTFM built but all CCA scores reset to 0.5 (uniform)
  "no_synthesis" — Ablation B: CTFM available but plan generated by BM25 retrieval
                   (same knowledge, different planning mechanism)
  "no_ctfm"      — Ablation C: No learned model; pure task-type rule-based hints
"""
from __future__ import annotations

import logging
from typing import Optional

from ..shared.prompt_builder import PromptAugmenter
from .causal_graph import CausalGraphSynthesizer
from .tool_function_model import CTFMStore, ToolFunctionModel

logger = logging.getLogger(__name__)

_ABLATION_MODES = frozenset({"no_cca", "no_synthesis", "no_ctfm"})


def _normalize_ctfm_slugs(models: "dict[str, ToolFunctionModel]") -> "dict[str, ToolFunctionModel]":
    """Filter CTFM models to only those whose slugs exist in the current registry.

    Builds a tool-name → slug lookup for unambiguous cases so that stale
    toolkit prefixes (e.g. "geo_raster" → "georaster") are remapped automatically.
    Tools with no registry match (e.g. "DisplayOnGeotiff") are dropped.
    """
    try:
        from ...core.registry import registry
        from ...extensions import load_builtin_toolkits
        load_builtin_toolkits()
        valid_slugs: set[str] = {spec.slug for spec in registry.list_tools()}
    except Exception:
        return models  # registry unavailable — use as-is

    # Build unambiguous tool-name → slug map (name = part after first dot)
    name_to_slug: dict[str, str] = {}
    for slug in valid_slugs:
        if "." in slug:
            name = slug.split(".", 1)[1]
            if name in name_to_slug:
                name_to_slug[name] = ""   # ambiguous — don't use
            else:
                name_to_slug[name] = slug

    def _resolve(s: str) -> "Optional[str]":
        if s in valid_slugs:
            return s
        if "." in s:
            name = s.split(".", 1)[1]
            resolved = name_to_slug.get(name, "")
            return resolved or None
        return None

    normalized: "dict[str, ToolFunctionModel]" = {}
    for old_slug, model in models.items():
        new_slug = _resolve(old_slug)
        if not new_slug:
            continue
        model.tool_slug = new_slug
        model.downstream_tools = [r for t in model.downstream_tools if (r := _resolve(t))]
        model.upstream_tools = [r for t in model.upstream_tools if (r := _resolve(t))]
        normalized[new_slug] = model

    logger.debug(f"CTFM slug normalization: {len(models)} raw → {len(normalized)} valid models")
    return normalized


def _infer_task_type(question: str) -> str:
    q = question.lower()
    if any(kw in q for kw in ["change", "compare", "difference", "before", "after"]):
        return "change_detection"
    if any(kw in q for kw in ["nearest", "route", "closest", "station", "poi", "facility"]):
        return "poi_routing"
    if any(kw in q for kw in ["detect", "segment", "count", "object"]):
        return "segmentation"
    if any(kw in q for kw in ["ndvi", "ndbi", "ndwi", "nbr", "index", "calculate", "raster"]):
        return "index_calculation"
    if any(kw in q for kw in ["image", "satellite", "aerial", "scene", "identify", "classify"]):
        return "scene_classification"
    return "general_qa"


class CausalEvoPromptInjector(PromptAugmenter):
    """Injects a causal execution plan and CTFM hints into the system prompt."""

    def __init__(
        self,
        store: CTFMStore,
        top_k: int = 5,
        use_ablation: Optional[str] = None,
    ) -> None:
        """
        Args:
            store:        CTFMStore with pre-built tool function models.
            top_k:        Max tools to include in the synthesized plan.
            use_ablation: Ablation identifier or None for full CausalEvo.
        """
        if use_ablation is not None and use_ablation not in _ABLATION_MODES:
            raise ValueError(f"use_ablation must be one of {_ABLATION_MODES} or None")
        self._store = store
        self._top_k = top_k
        self._ablation = use_ablation
        self._models: Optional[dict[str, ToolFunctionModel]] = None
        self._synthesizer: Optional[CausalGraphSynthesizer] = None

    # ------------------------------------------------------------------ #
    # PromptAugmenter interface                                            #
    # ------------------------------------------------------------------ #

    def augment(
        self,
        user_query: str,
        images: Optional[list[str]] = None,
        task_type: Optional[str] = None,
        **kwargs,
    ) -> str:
        """Return augmented system prompt with causal plan injected."""
        self._ensure_loaded()
        task_type = task_type or _infer_task_type(user_query)

        if self._ablation == "no_synthesis":
            hint = self._bm25_hint(user_query, task_type)
        elif self._ablation == "no_ctfm":
            hint = self._rule_based_hint(user_query, task_type)
        else:
            # Full CausalEvo (no_cca variant handled at load time)
            hint = self._synthesizer.format_plan_hint(user_query, task_type, top_k=self._top_k)

        return self.BASE_SYSTEM + hint

    # ------------------------------------------------------------------ #
    # Online update                                                        #
    # ------------------------------------------------------------------ #

    def record_outcome(
        self,
        query: str,
        tools_called: list[str],
        reward: float,
        task_type: Optional[str] = None,
    ) -> None:
        """Incrementally update CTFM success_rate after an episode (online mode).

        Lightweight: adjusts n_success_obs / n_failure_obs counters and
        recomputes success_rate.  Full CCA / keyword rebuild only happens
        in batch via runner.cmd_build().
        """
        if not self._models:
            return
        success = reward >= 0.5
        for tool in tools_called:
            if tool in self._models:
                m = self._models[tool]
                if success:
                    m.n_success_obs += 1
                else:
                    m.n_failure_obs += 1
                total = m.n_success_obs + m.n_failure_obs
                m.success_rate = m.n_success_obs / total if total else 0.5
        try:
            self._store.save(self._models)
        except Exception as e:
            logger.debug(f"CTFM online save error: {e}")

    # ------------------------------------------------------------------ #
    # Internals                                                            #
    # ------------------------------------------------------------------ #

    def _ensure_loaded(self) -> None:
        if self._models is not None:
            return
        self._models = self._store.load()

        if self._ablation == "no_ctfm":
            self._models = {}           # empty → rule-based fallback
        elif self._ablation == "no_cca":
            for m in self._models.values():
                m.avg_cca_score = 0.5   # reset causal importance to uniform

        # Normalize stored slugs against the current registry so stale/renamed
        # tool names (e.g. "geo_raster.calculate_index" vs "georaster.calculate_index")
        # don't leak into the generated plan and mislead the LLM.
        self._models = _normalize_ctfm_slugs(self._models)

        self._synthesizer = CausalGraphSynthesizer(self._models)

    def _bm25_hint(self, query: str, task_type: str) -> str:
        """Ablation B: BM25-style keyword retrieval from CTFM (no causal synthesis)."""
        if not self._models:
            return ""
        q_words = {w.strip(".,!?;:\"'()[]").lower() for w in query.split()}
        scored = []
        for slug, m in self._models.items():
            kw_set = {kw.lower() for kw in m.precondition_keywords}
            overlap = len(q_words & kw_set)
            scored.append((overlap, slug, m))
        scored.sort(key=lambda x: x[0], reverse=True)
        top = scored[: self._top_k]
        if not top or top[0][0] == 0:
            return ""
        lines = ["\n\n## Tool Suggestions (BM25 Retrieval — Ablation B)"]
        for overlap, slug, m in top:
            lines.append(
                f"  • {slug}  (keyword overlap={overlap}, "
                f"success rate={m.success_rate:.2f})"
            )
        return "\n".join(lines)

    def _rule_based_hint(self, query: str, task_type: str) -> str:
        """Ablation C: pure task-type heuristic, no learned CTFM."""
        q = query.lower()
        lines = ["\n\n## Task Guidance (Rule-Based — Ablation C)"]
        if "boundary" in q or "area" in q or "region" in q or "city" in q:
            lines.append(
                "This is a geospatial query. Suggested start: osm_gis.get_area_boundary "
                "to retrieve the region, then use relevant analysis tools."
            )
        elif any(kw in q for kw in ["ndvi", "ndwi", "nbr", "index"]):
            lines.append(
                "Raster index task. Suggested order: "
                "osm_gis.get_area_boundary → georaster.get_raster → georaster.calculate_index"
            )
        elif any(kw in q for kw in ["change", "before", "after", "compare"]):
            lines.append(
                "Change detection task. Suggested: get boundary, fetch two temporal rasters, "
                "then compare."
            )
        elif any(kw in q for kw in ["image", "satellite", "aerial", "scene"]):
            lines.append(
                "Image analysis task. Start with vlm_analyze for scene understanding."
            )
        else:
            lines.append(
                "No specific rule matched. Consider osm_gis.get_area_boundary if a location "
                "is mentioned, or vlm_analyze if images are provided."
            )
        return "\n".join(lines)
